version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mks
      MONGO_INITDB_ROOT_PASSWORD: this_is_password
    volumes:
      - ./data/mongodb:/data/db
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=mks
      - POSTGRES_PASSWORD=this_is_password
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
