version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mks
      MONGO_INITDB_ROOT_PASSWORD: this_is_password
  #    volumes:
  #      - ./data/mongodb:/data/db
  mongodb_test:
    image: mongo:latest
    restart: always
    container_name: mongo_test
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mks
      MONGO_INITDB_ROOT_PASSWORD: this_is_password
  #    volumes:
  #      - ./data/mongodb:/data/db
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=mks
      - POSTGRES_PASSWORD=this_is_password
  #    volumes:
  #      - ./data/postgres:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - .:/backend
    restart: always
    container_name: backend
    ports:
      - "8000:8000"